title: Wanxuan Li's Homepage
page-top-title: WanxuanLi
top-section-bg-text: Technology and Health
home-subtitle: Wanxuan Li&ensp;|&ensp;李宛璇
copyright-text: '&copy; Wanxuan Li 2020-2025. All Rights Reserved.'
